# Model url
# if load from state dict set url False
url : https://github.com/benihime91/retinanet_pet_detector/releases/download/v0.0.1/resnet18-2020-08-04-ffdde352.pth
# wether to load from url or state_dict
load_from_url: True
# if load from url is False
# state_dict path must be given
state_dict_path : False
# resnet backbone for retinanet
model_backbone: 'resnet18'
num_classes : 37 # this is the number of unique classes in oxford IITG pets dataset
