## For resnet50
# url: should contain either the url where the model weights are saved
# or the path to the model weights
model_backbone: "resnet50"
url: https://github.com/benihime91/retinanet_pet_detector/releases/download/v0.0.1/resnet50-2020-09-20-ver0.pth
num_classes: 37
